plugins {
    // Dynamic Plugin ID and Version
    id "${project.loom_plugin_id}" version "${project.loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    
    // Only use mappings if NOT on 26.1 (Unobfuscated)
    if (project.minecraft_version != "26.1") {
        mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    }
    
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

java {
    // Dynamically sets the Java target based on your properties
    sourceCompatibility = JavaVersion.toVersion(project.java_version)
    targetCompatibility = JavaVersion.toVersion(project.java_version)
}
